name: bambooapp
description: A Flutter app for bamboo classification.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2 # Recommended to use latest stable version
  camera: ^0.9.4+5 # Keep if you plan to use direct camera access
  tflite_flutter: ^0.10.1 # Make sure this is ^0.10.1
  image: ^4.2.0 # Make sure this is ^4.2.0
  path_provider: ^2.0.8
  # NO tflite_flutter_helper HERE ANYMORE!
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/labels.txt # Assuming you have a labels file