name: bambooapp
description: A Flutter app for bamboo classification.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  image: ^4.0.17
  path_provider: ^2.0.8
  percent_indicator: ^4.2.3
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/model.tflite
    - assets/labels.txt

  fonts:
    - family: BambooFont
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
